from typing import List, Dict, Any


def generate_executive_report(
    topic: str,
    summary_text: str,
    findings: List[Dict[str, Any]],
    citations: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Agent tool: Formats multi-document research findings into a standardized executive report.
    """
    report_md = f"""# EXECUTIVE REPORT: {topic.upper()}
**Generated by**: NEXUS Agentic Intelligence Engine
**Status**: Verified with Source Grounding

## 1. Executive Summary
{summary_text}

## 2. Key Policy & Technical Findings
"""
    for idx, f in enumerate(findings, 1):
        report_md += f"\n### {idx}. {f.get('title', 'Finding')}\n"
        report_md += f"- **Details**: {f.get('details', '')}\n"
        if f.get('impact'):
            report_md += f"- **Impact**: {f.get('impact')}\n"

    report_md += "\n## 3. Grounding & Evidence Sources\n"
    for c in citations:
        report_md += f"- [{c['filename']} — Page {c['page']} — {c.get('section', 'General')}]\n"

    return {
        "report_markdown": report_md,
        "citation_count": len(citations),
        "finding_count": len(findings)
    }
